name: Continuous Integration

on:
  push:
    paths:
      - Dockerfile
      - entrypoint.sh
    branches:
      - master

jobs:
  push-to-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v
    - uses: elgohr/Publish-Docker-Github-Action@master
      name: Publish to Docker
      with:
        name: mjamaah/kubectl
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        tags: latest,1.28.4
        cache: true